version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/environments/hub"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/environments/dev"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/environments/test"
    schedule:
      interval: "weekly"

  - package-ecosystem: "terraform"
    directory: "/environments/prod"
    schedule:
      interval: "weekly"